export const getPortfolioList = (t: (key: string) => string) => [
  {
    folder: "casamento-felipe-e-juan-alem-do-sonho",
    title: t("portfolioList.felipe.title"),
    subtitle: t("portfolioList.felipe.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-felipe-e-juan-alem-do-sonho/port-felipe-juan-capa.jpg`,
  },
  {
    folder: "ana-paula-e-lucas---villa-riso",
    title: t("portfolioList.anaPaula.title"),
    subtitle: t("portfolioList.anaPaula.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/ana-paula-e-lucas---villa-riso/P1099427.JPG`,
  },
  {
    folder: "Raquel-e-Leonel-Alem-do-Sonho",
    title: t("portfolioList.raquel.title"),
    subtitle: t("portfolioList.raquel.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Raquel-e-Leonel-Alem-do-Sonho/image00066.JPEG`,
  },
  {
    folder: "Jaluza-e-Luiz-Solar-real",
    title: t("portfolioList.jaluza.title"),
    subtitle: t("portfolioList.jaluza.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Jaluza-e-Luiz-Solar-real/G3O7xqNyQNQ6kRON0cXORglTvb-LWpFw.jpg`,
  },
  {
    folder: "beatriz-15-anos---golden-green",
    title: t("portfolioList.beatriz15.title"),
    subtitle: t("portfolioList.beatriz15.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/beatriz-15-anos---golden-green/BC-42.JPEG`,
  },
  {
    folder: "Camila_e_Pedro_Haras_Pedra_do_Elefante",
    title: t("portfolioList.camilaPedro.title"),
    subtitle: t("portfolioList.camilaPedro.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Camila_e_Pedro_Haras_Pedra_do_Elefante/CHU20913.jpg`,
  },
  {
    folder: "Camila-e-Joao-Juiz-de-Fora",
    title: t("portfolioList.camilaJoao.title"),
    subtitle: t("portfolioList.camilaJoao.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Camila-e-Joao-Juiz-de-Fora/TR2_4023.JPEG`,
  },
  {
    folder: "Camille-e-Erick-Lago-Buriti",
    title: t("portfolioList.camille.title"),
    subtitle: t("portfolioList.camille.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Camille-e-Erick-Lago-Buriti/IMG_4670.JPG`,
  },
  {
    folder: "casamento-larissa-e-chicri---itanhanga-golfe-club",
    title: t("portfolioList.larissa.title"),
    subtitle: t("portfolioList.larissa.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-larissa-e-chicri---itanhanga-golfe-club/LARISSAELUIZFELIPE_PREVIA_CERIMONIA(30de63).jpg`,
  },
  {
    folder: "casamento-louhayne-e-charles---igreja-sao-francisco-de-paula",
    title: t("portfolioList.louhayne.title"),
    subtitle: t("portfolioList.louhayne.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-louhayne-e-charles---igreja-sao-francisco-de-paula/IMG_6826.JPG`,
  },
  {
    folder: "casamento-mariana-e-mario-cristo-redentor",
    title: t("portfolioList.mariana.title"),
    subtitle: t("portfolioList.mariana.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-mariana-e-mario-cristo-redentor/@pchufi-314.JPEG`,
  },
  {
    folder: "casamento-rhaynna-e-lucas---golfe-olimpico",
    title: t("portfolioList.rhayanna.title"),
    subtitle: t("portfolioList.rhayanna.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-rhaynna-e-lucas---golfe-olimpico/WhatsApp%20Image%202022-05-31%20at%2010.47.21%20(2).jpeg`,
  },
  {
    folder: "Sarah-e-Rodrigo-Santa-Teresa-MGallery",
    title: t("portfolioList.sarah.title"),
    subtitle: t("portfolioList.sarah.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Sarah-e-Rodrigo-Santa-Teresa-MGallery/sarah-rodrigo-wed-87.jpg`,
  },
  {
    folder: "beatriz-e-kenedy-Alem-do-Sonho",
    title: t("portfolioList.beatrizKenedy.title"),
    subtitle: t("portfolioList.beatrizKenedy.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/beatriz-e-kenedy-Alem-do-Sonho/IMG_1189.JPG`,
  },
  {
    folder: "Catharina-15-anos-Jockey-Pareo",
    title: t("portfolioList.catharina.title"),
    subtitle: t("portfolioList.catharina.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Catharina-15-anos-Jockey-Pareo/Catharina__0597.JPEG`,
  },
];
