export const getPortfolioList = (t: (key: string) => string) => [
  {
    folder: "casamento-felipe-e-juan-alem-do-sonho",
    title: t("portfolioList.felipe.title"),
    subtitle: t("portfolioList.felipe.subtitle"),
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-felipe-e-juan-alem-do-sonho/port-felipe-juan-capa.jpg`,
  },
  {
    folder: "ana-paula-e-lucas---villa-riso",
    title: "ANA PAULA & LUCAS",
    subtitle: "CASAMENTO ANA PAULA & LUCAS - VILLA RISO",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/ana-paula-e-lucas---villa-riso/P1099427.JPG`,
  },
  {
    folder: "Raquel-e-Leonel-Alem-do-Sonho",
    title: "RAQUEL & LEONEL",
    subtitle: "CASAMENTO RAQUEL & LEONEL - ALÉM DO SONHO",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Raquel-e-Leonel-Alem-do-Sonho/image00066.JPEG`,
  },
  {
    folder: "Januza-e-Luiz-Solar-real",
    title: "JANUZA & LUIZ",
    subtitle: "CASAMENTO JANUZA & LUIZ - SOLAR REAL",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Januza-e-Luiz-Solar-real/G3O7xqNyQNQ6kRON0cXORglTvb-LWpFw.jpg`,
  },
  {
    folder: "beatriz-15-anos---golden-green",
    title: "BEATRIZ - 15 ANOS",
    subtitle: "BEATRIZ - 15 ANOS - GOLDEN GREEN",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/beatriz-15-anos---golden-green/BC-42.JPEG`,
  },
  {
    folder: "Camila_e_Pedro_Haras_Pedra_do_Elefante",
    title: "CAMILA & PEDRO",
    subtitle: "CASAMENTO CAMILA & PEDRO - HARAS PEDRA DO ELEFANTE",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Camila_e_Pedro_Haras_Pedra_do_Elefante%20/CAMILA%20E%20PEDRO_CHU20716.jpg`,
  },
  {
    folder: "Camila-e-Joao-Juiz-de-Fora",
    title: "CAMILA & JOÃO",
    subtitle: "CASAMENTO CAMILA & JOÃO - JUIZ DE FORA",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Camila-e-Joao-Juiz-de-Fora%20/CASAMENTO%20CAMILA%20E%20JOAO%20GABRIEL_264.JPEG`,
  },
  {
    folder: "Camille-e-Erick-Lago-Buriti",
    title: "CAMILLE & ERICK",
    subtitle: "CASAMENTO CAMILLE & ERICK - LAGO BURITI",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Camille-e-Erick-Lago-Buriti/IMG_4670.JPG`,
  },
  {
    folder: "casamento-larissa-&-chicri---itanhanga-golfe-club",
    title: "LARISSA & CHICRI",
    subtitle: "CASAMENTO LARISSA & CHICRI - ITANHANGÁ GOLF CLUB",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-larissa-&-chicri---itanhanga-golfe-club/LARISSAELUIZFELIPE_PREVIA_CERIMONIA(30de63).jpg`,
  },
  {
    folder: "casamento-louhayne-e-charles---igreja-sao-francisco-de-paula",
    title: "LOUHAYNE & CHARLES",
    subtitle: "CASAMENTO LOUHAYNE & CHARLES - IGREJA SÃO FRANCISCO DE PAULA",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-louhayne-e-charles---igreja-sao-francisco-de-paula/IMG_6826.JPG`,
  },
  {
    folder: "casamento-mariana-&-mario-cristo-redentor",
    title: "MARIANA & MARIO",
    subtitle: "CASAMENTO MARIANA & MARIO - CRISTO REDENTOR",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-mariana-&-mario-cristo-redentor/@pchufi-314.JPEG`,
  },
  {
    folder: "casamento-rhaynna-&-lucas---golfe-olimpico",
    title: "RHAYANNA & LUCAS",
    subtitle: "CASAMENTO RHAYANNA & LUCAS - GOLFE OLÍMPICO",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/casamento-rhaynna-&-lucas---golfe-olimpico/WhatsApp%20Image%202022-05-31%20at%2010.47.21%20(2).jpeg`,
  },
  {
    folder: "Sarah-e-Rodrigo-Santa-Teresa-MGallery",
    title: "SARAH & RODRIGO",
    subtitle: "CASAMENTO SARAH & RODRIGO - SANTA TERESA MGALLERY",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Sarah-e-Rodrigo-Santa-Teresa-MGallery/sarah-rodrigo-wed-87.jpg`,
  },
  {
    folder: "januza-e-luiz-no-solar-real",
    title: "JANUZA & LUIZ",
    subtitle: "CASAMENTO JANUSA & LUIZ - SOLAR  REAL",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Januza-e-Luiz-Solar-real/G3O7xqNyQNQ6kRON0cXORglTvb-LWpFw.jpg`,
  },
  {
    folder: "beatriz-e-kenedy-Alem-do-Sonho",
    title: "BEATRIZ & KENEDY",
    subtitle: "CASAMENTO BEATRIZ & KENEDY - ALÉM DO SONHO",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/beatriz-e-kenedy-Alem-do-Sonho%20/IMG_1163.JPG`,
  },
  {
    folder: "Catharina-15-anos-Jockey-Pareo",
    title: "CATHARINA - 15 ANOS",
    subtitle: "CATHARINA - 15 ANOS - JOCKEY PAREO",
    image: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/portfolio/Catharina-15-anos-Jockey-Pareo/Catharina__0597.JPEG`,
  },
];
